### ISSUE TITLE
mod_log_net.so: undefined symbol: libiconv

### ISSUE THREAD

**Issue by cbrassel** [fbacchella/mod_log_net#3]
Hi,

I have compile whit out trouble .. but it seem's I can not load the module, here is what I have done ..

`./configure --with-apxs=/product/httpd-2.4.23/bin/apxs
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: Locating apxs
checking for --with-apxs... /product/httpd-2.4.23/bin/apxs
configure: apxs found at /product/httpd-2.4.23/bin/apxs
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking for library containing iconv_open... none required
checking msgpack.h usability... yes
checking msgpack.h presence... yes
checking for msgpack.h... yes
checking for library containing msgpack_version... -lmsgpackc
checking for memcpy... yes
configure: creating ./config.status
config.status: creating Makefile
root@w1:/product-install/mod_log_net-master# make
/product/httpd-2.4.23/bin/apxs -c -lmsgpackc  -Wc,"-Wall  -g -O2 -Wno-unused-function " -Wl,"" mod_log_net.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic   -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/product/httpd-2.4.23/include  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -Wall  -g -O2 -Wno-unused-function   -c -o mod_log_net.lo mod_log_net.c && touch mod_log_net.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link x86_64-linux-gnu-gcc -std=gnu99    -o mod_log_net.la   -lmsgpackc -rpath /product/httpd-2.4.23/modules -module -avoid-version    mod_log_net.lo
root@w1:/product-install/mod_log_net-master# make install
if test ! -d /product/httpd-2.4.23/modules; then mkdir -p /product/httpd-2.4.23/modules; fi
/product/httpd-2.4.23/bin/apxs -i -S LIBEXECDIR=/product/httpd-2.4.23/modules mod_log_net.la
/product/httpd-2.4.23/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' mod_log_net.la /product/httpd-2.4.23/modules
/usr/share/apr-1.0/build/libtool --mode=install install mod_log_net.la /product/httpd-2.4.23/modules/
libtool: install: install .libs/mod_log_net.so /product/httpd-2.4.23/modules/mod_log_net.so
libtool: install: install .libs/mod_log_net.lai /product/httpd-2.4.23/modules/mod_log_net.la
libtool: install: install .libs/mod_log_net.a /product/httpd-2.4.23/modules/mod_log_net.a
libtool: install: chmod 644 /product/httpd-2.4.23/modules/mod_log_net.a
libtool: install: ranlib /product/httpd-2.4.23/modules/mod_log_net.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/sbin" ldconfig -n /product/httpd-2.4.23/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /product/httpd-2.4.23/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 755 /product/httpd-2.4.23/modules/mod_log_net.so
root@w1:/product-install/mod_log_net-master# rcapache2 restart
Restarting apache
httpd: Syntax error on line 75 of /product/etc/httpd/httpd.conf: Cannot load /product/httpd-2.4.23/modules/mod_log_net.so into server: /product/httpd-2.4.23/modules/mod_log_net.so: undefined symbol: libiconv
root@w1:/# ldd /product/httpd-2.4.23/modules/mod_log_net.so
	linux-vdso.so.1 =>  (0x00007fff607ff000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0710acf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f07110a0000)
`

Any Idea where the problem can be ?

**Comment by fbacchella** [comment]
You're bug report is hard to understand, can you please clean it ?

Any way, for some reason, configure says:

    checking for library containing iconv_open... none required

But when apache start:

   2.4.23/modules/mod_log_net.so into server: /product/httpd-2.4.23/modules/mod_log_net.so: undefined symbol: libiconv

But again, so much bold in in your bug report, what's this stuff about LIBDIR and  doing here, in the middle of you report ?
On what system are you running ?

**Comment by cbrassel** [comment]
Hi, sorry for the formating .. no idea why it's in bold ..

to resume, I try to compile on ubuntu 12.04.5 LTS
i have installed msgpack bbuntu package : libmsgpack3, Version: 0.5.4-2
and the libiconv-1.14 from source
apache is in version 2.4.23
And i have no idea why he didn't find the iconv_open, I have checked in the library theyre are the iconv_open .. so I don't now ..

**Comment by fbacchella** [comment]
Try remove the source installation. iconv tools are part of glibc, so I don't think you need to install it. Try searching the headers in the standards package from ubuntu.

**Comment by fbacchella** [comment]
Your libmsgpack3 is too old. I wonder if it might be the real problem.
Can you try to remove manual installation of iconv and upgrade msgpack.
